[package]
name = "yee-multi-miner"
version = "0.1.0"
authors = ["YeeCo <contact@yeefoundation.com>"]
edition = "2018"

[dependencies]
numext-fixed-hash = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
faketime = "0.2.0"
rand = "0.6"
byteorder = "1.3.1"
serde = "1.0"
serde_derive = "1.0"
crossbeam-channel = "0.3"
fnv = "1.0.3"
serde_json = "1.0"
hyper = "0.12"
failure = "0.1.5"
yee-stop-handler = { package = "yee-stop-handler", path = "../util/stop-handler" }
yee-jsonrpc-types = { package = "yee-jsonrpc-types", path = "../util/jsonrpc-types" }
lru-cache = { package = "lru-cache", path = "../util/lru-cache" }
util = { package = "util", path = "../util" }
primitives = { package = "substrate-primitives", git = "https://github.com/yeeco/substrate.git", branch = "v1.0" }
tokio = "0.1.7"
exit-future = "0.1"
futures = "0.1"
log = "0.4"
uuid = { version = "0.7", features = ["serde", "v4"] }
