[package]
name = "util"
version = "0.1.0"
authors = ["YeeCo <contact@yeefoundation.com>"]
edition = "2018"


[dependencies]
parking_lot = {version = "=0.7.1", features = ["deadlock_detection"]}
fnv = "1.0.3"

