[package]
name = "yee-stop-handler"
version = "0.1.0"
authors = ["YeeCo <contact@yeefoundation.com>"]
edition = "2018"

[dependencies]
parking_lot = "=0.7.1"
crossbeam-channel = "0.3"
futures = "0.1"
